from importlib import resources
from phenopacket_mapper.data_standards import DataModel, DataField
from phenopacket_mapper.data_standards.value_set import ValueSet

rarelink_cdm_2_0 = DataModel(
    data_model_name="RareLink Common Data Model 2.0",
    fields=[DataField(name="temp", value_set=ValueSet())],
    resources=resources,
)
#     fields=[
#         # 1. Formal Criteria
#         DataField(section="1. Formal Criteria", ordinal="1.1", 
#                    name="Pseudonym", value_set=vs_1_1),
#         DataField(section="1. Formal Criteria", ordinal="1.2", 
#                    name="Date of Admission", value_set=vs_1_2),

#         # 2. Personal Information
#         DataField(section="2. Personal Information", ordinal="2.1", 
#                    name="Date of Birth", value_set=vs_2_1),
#         DataField(section="2. Personal Information", ordinal="2.2", 
#                    name="Sex at Birth", value_set=vs_2_2),
#         DataField(section="2. Personal Information", ordinal="2.3", 
#                    name="Karyotypic Sex", value_set=vs_2_3),
#         DataField(section="2. Personal Information", ordinal="2.4", 
#                    name="Gender Identity", value_set=vs_2_4),

#         # 3. Patient Status
#         DataField(section="3. Patient Status", ordinal="3.1", 
#                    name="Vital Status", value_set=vs_3_1),
#         DataField(section="3. Patient Status", ordinal="3.2", 
#                    name="Time of Death", value_set=vs_3_2),
#         DataField(section="3. Patient Status", ordinal="3.3", 
#                    name="Cause of Death", value_set=vs_3_3),
#         DataField(section="3. Patient Status", ordinal="3.4", 
#                    name="Age Category", value_set=vs_3_4),
#         DataField(section="3. Patient Status", ordinal="3.5", 
#                    name="Length of Gestation at Birth", value_set=vs_3_5),
#         DataField(section="3. Patient Status", ordinal="3.6", 
#                    name="Undiagnosed RD Case", value_set=vs_3_6),

#         # 4. Care Pathway
#         DataField(section="4. Care Pathway", ordinal="4.1", 
#                    name="Encounter Start", value_set=vs_4_1),
#         DataField(section="4. Care Pathway", ordinal="4.2", 
#                    name="Encounter End", value_set=vs_4_2),
#         DataField(section="4. Care Pathway", ordinal="4.3", 
#                    name="Encounter Status", value_set=vs_4_3),
#         DataField(section="4. Care Pathway", ordinal="4.4", 
#                    name="Encounter Class", value_set=vs_4_4),

#         # 5. Disease
#         DataField(section="5. Disease", ordinal="5.1", 
#                    name="Disease", value_set=vs_5_1),
#         DataField(section="5. Disease", ordinal="5.2", 
#                    name="Verification Status", value_set=vs_5_2),
#         DataField(section="5. Disease", ordinal="5.3", 
#                    name="Age at Onset", value_set=vs_5_3),
#         DataField(section="5. Disease", ordinal="5.4", 
#                    name="Date of Onset", value_set=vs_5_4),
#         DataField(section="5. Disease", ordinal="5.5", 
#                    name="Age at Diagnosis", value_set=vs_5_5),
#         DataField(section="5. Disease", ordinal="5.6", 
#                    name="Date of Diagnosis", value_set=vs_5_6),
#         DataField(section="5. Disease", ordinal="5.7", 
#                    name="Body Site [SNOMED CT]", value_set=vs_5_7),
#         DataField(section="5. Disease", ordinal="5.8", 
#                    name="Clinical Status", value_set=vs_5_8),
#         DataField(section="5. Disease", ordinal="5.9", 
#                    name="Severity", value_set=vs_5_9),

#         # 6.1 Genetic Findings
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.1", 
#                    name="Genomic Diagnosis [MONDO]", value_set=vs_6_1_1),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.2", 
#                    name="Progress Status of Interpretation", value_set=vs_6_1_2),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.3", 
#                    name="Interpretation Status", value_set=vs_6_1_3),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.4", 
#                    name="Structural Variant Analysis Method", value_set=vs_6_1_4),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.5", 
#                    name="Reference Genome", value_set=vs_6_1_5),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.6", 
#                    name="Genetic Mutation String", value_set=vs_6_1_6),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.7", 
#                    name="Genomic DNA Change [g.HGVS]", value_set=vs_6_1_7),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.8", 
#                    name="Sequence DNA Change [c.HGVS]", value_set=vs_6_1_8),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.9", 
#                    name="Amino Acid Change [p.HGVS]", value_set=vs_6_1_9),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.10", 
#                    name="Gene [HGNC-NR]", value_set=vs_6_1_10),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.11", 
#                    name="Zygosity", value_set=vs_6_1_11),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.12", 
#                    name="Genomic Source Class", value_set=vs_6_1_12),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.13", 
#                    name="DNA Change Type", value_set=vs_6_1_13),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.14", 
#                    name="Clinical Significance [ACMG]", value_set=vs_6_1_14),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.15", 
#                    name="Therapeutic Actionability", value_set=vs_6_1_15),
#         DataField(section="6.1 Genetic Findings", ordinal="6.1.16", 
#                    name="Clinical Annotation Level Of Evidence", value_set=vs_6_1_16),

#         # 6.2 Phenotypic Feature
#         DataField(section="6.2 Phenotypic Feature", ordinal="6.2.1", 
#                    name="Phenotypic Feature", value_set=vs_6_2_1),
#         DataField(section="6.2 Phenotypic Feature", ordinal="6.2.2", 
#                    name="Determination Date", value_set=vs_6_2_2),
#         DataField(section="6.2 Phenotypic Feature", ordinal="6.2.3", 
#                    name="Status", value_set=vs_6_2_3),
#         DataField(section="6.2 Phenotypic Feature", ordinal="6.2.4", 
#                    name="Modifier", value_set=vs_6_2_4),

#         # 6.3 Family History
#         DataField(section="6.3 Family History", ordinal="6.3.0", 
#                    name="Family Member Pseudonym", value_set=vs_6_3_0),
#         DataField(section="6.3 Family History", ordinal="6.3.1", 
#                    name="Propositus/-a", value_set=vs_6_3_1),
#         DataField(section="6.3 Family History", ordinal="6.3.2", 
#                    name="Relationship of the individual to the index case / propositus/a", 
#                    value_set=vs_6_3_2),
#         DataField(section="6.3 Family History", ordinal="6.3.3", 
#                    name="Consanguinity", value_set=vs_6_3_3),
#         DataField(section="6.3 Family History", ordinal="6.3.4", 
#                    name="Family Member Relationship", value_set=vs_6_3_4),
#         DataField(section="6.3 Family History", ordinal="6.3.5", 
#                    name="Family Member Record Status", value_set=vs_6_3_5),
#         DataField(section="6.3 Family History", ordinal="6.3.6", 
#                    name="Family Member Sex", value_set=vs_6_3_6),
#         DataField(section="6.3 Family History", ordinal="6.3.7", 
#                    name="Family Member Age", value_set=vs_6_3_7),
#         DataField(section="6.3 Family History", ordinal="6.3.8", 
#                    name="Family Member Date of Birth", value_set=vs_6_3_8),
#         DataField(section="6.3 Family History", ordinal="6.3.9", 
#                    name="Family Member Deceased", value_set=vs_6_3_9),
#         DataField(section="6.3 Family History", ordinal="6.3.10", 
#                    name="Family Member Cause of Death [ICD10CM]", value_set=vs_6_3_10),
#         DataField(section="6.3 Family History", ordinal="6.3.11", 
#                    name="Family Member Deceased Age", value_set=vs_6_3_11),
#         DataField(section="6.3 Family History", ordinal="6.3.12", 
#                    name="Family Member Disease [MONDO]", value_set=vs_6_3_12),

#         # 7. Consent
#         DataField(section="7. Consent", ordinal="7.1", 
#                    name="Consent Status", value_set=vs_7_1),
#         DataField(section="7. Consent", ordinal="7.2", 
#                    name="Consent Date", value_set=vs_7_2),
#         DataField(section="7. Consent", ordinal="7.3", 
#                    name="Health Policy Monitoring", value_set=vs_7_3),
#         DataField(section="7. Consent", ordinal="7.4", 
#                    name="Agreement to be contacted for research purposes", 
#                    value_set=vs_7_4),
#         DataField(section="7. Consent", ordinal="7.5", 
#                    name="Consent to the reuse of data", 
#                    value_set=vs_7_5),
#         DataField(section="7. Consent", ordinal="7.6", 
#                    name="Biological sample", 
#                    value_set=vs_7_6),
#         DataField(section="7. Consent", ordinal="7.7", 
#                    name="Link to a biobank", 
#                    value_set=vs_7_7),

#         # 8. Classification of functioning / disability
#         DataField(section="8. Classification", ordinal="8.1", 
#                    name="Classification of functioning / disability", 
#                    value_set=vs_8_1),
#     ]
# )
  # TODO @aslgrafe: replace with finished datamodel