canonical: https://github.com/BIH-CEI/RareLink
id: rarelink-ig
name: RareLinkImplementationGuide
title: "RareLink Implementation Guide" # Optional, but recommended for clarity
description: >
  An Implementation Guide for RareLink Common Data Model, based on HL7 FHIR
  and the IPS 2.0.0 profiles, harmonizing international rare disease registries.
version: 2.0.0-dev0
status: active
copyrightYear: 2024
releaseLabel: dev0
fhirVersion: 4.0.1 # Specify the FHIR version you are using
dependencies:
  hl7.fhir.r4.core: # Core FHIR package
    uri: http://hl7.org/fhir/R4/
    version: 4.0.1
  hl7.fhir.uv.ips: # Reference for official IPS repository (1.1.0)
    uri: https://build.fhir.org/ig/HL7/fhir-ips/
    version: 1.1.0
  ips-2.0.0: # Local reference for IPS 2.0.0 (manually integrated)
    uri: https://build.fhir.org/ig/HL7/fhir-ips/
    version: 2.0.0
menu:
  - name: Home
    url: index.html
  - name: Profiles
    url: profiles.html
