canonical: https://github.com/BIH-CEI/RareLink
id: rarelink-ig
name: RareLinkImplementationGuide
title: "RareLink Implementation Guide"
description: >
  An Implementation Guide for RareLink Common Data Model, based on HL7 FHIR
  and the IPS 2.0.0 profiles, harmonizing international rare disease registries.
version: 2.0.0-dev0
status: active
copyrightYear: 2025
releaseLabel: 2.0.0.dev0
fhirVersion: 4.0.1 
dependencies:
  hl7.fhir.r4.core:
    uri: http://hl7.org/fhir/StructureDefinition/uri
    version: 4.0.1
  hl7.fhir.uv.ips:
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    version: 2.0.0
  hl7.fhir.uv.genomics-reporting:
    uri: http://hl7.org/fhir/uv/genomics-reporting/ImplementationGuide/hl7.fhir.uv.genomics-reporting
    version: 3.0.0
menu:
  - name: Home
    url: index.html
  - name: Profiles
    url: profiles.html
