
INFECTIONS_FEATURES_BLOCK = {
    "redcap_repeat_instrument": "infections_initial_form",
    "type_field": "infections_initial_form.snomedct_61274003",
    "type_field_2": "infections_initial_form.snomedct_21483005",
    "type_field_3": "infections_initial_form.snomedct_81745001",
    "type_field_4":" infections_initial_form.snomedct_385383008",
    "type_field_5": "infections_initial_form.snomedct_127856007",
    "type_field_6": "infections_initial_form.snomedct_110522009",
    "type_field_7": "infections_initial_form.snomedct_20139000",
    "type_field_8": "infections_initial_form.snomedct_303699009",
    "type_field_9": "infections_initial_form.snomedct_21514008",
    "type_field_10":"infections_initial_form.snomedct_31099001",
    "type_field_11": "infections_initial_form.other_infection_hpo",
    "type_field_12": "infections_initial_form.other_infection_mondo",
    "onset_date_fields": ["infections_initial_form.infection_date", 
                        "infections_initial_form.infection_date_2", 
                        "infections_initial_form.infection_date_3", 
                        "infections_initial_form.infection_date_4", 
                        "infections_initial_form.infection_date_5", 
                        "infections_initial_forminfection_date_6", 
                        "infections_initial_form.infection_date_7", 
                        "infections_initial_form.infection_date_8", 
                        "infections_initial_form.infection_date_9", 
                        "infections_initial_form.infection_date_10"],
    "severity_field": "infections_initial_form.infection_severity",
    "modifier_field_1": "infections_initial_form.type_of_infection",
    "modifier_field_2": "infections_initial_form.infection_temp_pattern",
    "modifier_field_4": "infections_initial_form.causing_agent_viral",
    "modifier_field_5": "infections_initial_formcausing_agent_bacterial",
    "modifier_field_6": "infections_initial_form.causing_agent_mycotic",
    "modifier_field_7": "infections_initial_form.causing_organism_other",
    "multi_onset": True
}



CONDITIONS_FEATURES_BLOCK = {
    "redcap_repeat_instrument": "patients_systemic_or_organ_specific_conditions",
    "type_field": "patients_systemic_or_organ_specific_conditions.snomedct_128477000",
    "type_field_1": "patients_systemic_or_organ_specific_conditions.snomedct_95320005",
    "type_field_2": "patients_systemic_or_organ_specific_conditions.snomedct_118938008",
    "type_field_3": "patients_systemic_or_organ_specific_conditions.snomedct_50043002",
    "type_field_4": "patients_systemic_or_organ_specific_conditions.snomedct_49601007",
    "type_field_5": "patients_systemic_or_organ_specific_conditions.mondo_0005570",
    "type_field_6": "patients_systemic_or_organ_specific_conditions.snomedct_928000",
    "type_field_7": "patients_systemic_or_organ_specific_conditions.snomedct_119292006",
    "type_field_8": "patients_systemic_or_organ_specific_conditions.snomedct_362969004",
    "type_field_9": "patients_systemic_or_organ_specific_conditions.snomedct_42030000",
    "type_field_10": "patients_systemic_or_organ_specific_conditions.snomedct_55342001",
    "type_field_11": "patients_systemic_or_organ_specific_conditions.snomedct_85828009",
    "type_field_12": "patients_systemic_or_organ_specific_conditions.hp_0025142",
    "type_field_13": "patients_systemic_or_organ_specific_conditions.snomedct_5294002",
    "type_field_14": "patients_systemic_or_organ_specific_conditions.condition_other_hp",
    "onset_date_field": "patients_systemic_or_organ_specific_conditions.condition_date_1",
    "severity_field": "patients_systemic_or_organ_specific_conditions.condition_severity",
    "modifier_field_1": "patients_systemic_or_organ_specific_conditions.type_of_condition",
    "modifier_field_2": "patients_systemic_or_organ_specific_conditions.hp_0012539_modifier",
    "modifier_field_3": "patients_systemic_or_organ_specific_conditions.hp_0012189_modifier",
    "modifier_field_4": "patients_systemic_or_organ_specific_conditions.hp_0005523_modifier",
    "modifier_field_5": "patients_systemic_or_organ_specific_conditions. condition_temp_patter",
    "evidence_field": "patients_systemic_or_organ_specific_conditions.mondo_0005265_evidence",   
}

PHENOTYPIC_FEATURES_BLOCK = {
    "redcap_repeat_instrument": "infections_initial_form",
    "type_field": "infections_initial_form.snomedct_61274003",
    "type_field_2": "infections_initial_form.snomedct_21483005",
    "type_field_3": "infections_initial_form.snomedct_81745001",
    "type_field_4":" infections_initial_form.snomedct_385383008",
    "type_field_5": "infections_initial_form.snomedct_127856007",
    "type_field_6": "infections_initial_form.snomedct_110522009",
    "type_field_7": "infections_initial_form.snomedct_20139000",
    "type_field_8": "infections_initial_form.snomedct_303699009",
    "type_field_9": "infections_initial_form.snomedct_21514008",
    "type_field_10":"infections_initial_form.snomedct_31099001",
    "type_field_11": "infections_initial_form.other_infection_hpo",
    "type_field_12": "infections_initial_form.other_infection_mondo",
    # Conditions
    # "type_field_13": "patients_systemic_or_organ_specific_conditions.snomedct_128477000",
    # "type_field_14": "patients_systemic_or_organ_specific_conditions.snomedct_95320005",
    # "type_field_15": "patients_systemic_or_organ_specific_conditions.snomedct_118938008",
    # "type_field_16": "patients_systemic_or_organ_specific_conditions.snomedct_50043002",
    # "type_field_17": "patients_systemic_or_organ_specific_conditions.snomedct_49601007",
    # "type_field_18": "patients_systemic_or_organ_specific_conditions.mondo_0005570",
    # "type_field_19": "patients_systemic_or_organ_specific_conditions.snomedct_928000",
    # "type_field_20": "patients_systemic_or_organ_specific_conditions.snomedct_119292006",
    # "type_field_21": "patients_systemic_or_organ_specific_conditions.snomedct_362969004",
    # "type_field_22": "patients_systemic_or_organ_specific_conditions.snomedct_42030000",
    # "type_field_23": "patients_systemic_or_organ_specific_conditions.snomedct_55342001",
    # "type_field_24": "patients_systemic_or_organ_specific_conditions.snomedct_85828009",
    # "type_field_25": "patients_systemic_or_organ_specific_conditions.hp_0025142",
    # "type_field_26": "patients_systemic_or_organ_specific_conditions.snomedct_5294002",
    # "type_field_27": "patients_systemic_or_organ_specific_conditions.condition_other_hp",
    
    # onset dates
    "onset_date_fields": ["infections_initial_form.infection_date", 
                          "infections_initial_form.infection_date_2", 
                          "infections_initial_form.infection_date_3", 
                          "infections_initial_form.infection_date_4", 
                          "infections_initial_form.infection_date_5", 
                          "infections_initial_forminfection_date_6", 
                          "infections_initial_form.infection_date_7", 
                          "infections_initial_form.infection_date_8", 
                          "infections_initial_form.infection_date_9", 
                          "infections_initial_form.infection_date_10",
    ],
    #                      "patients_systemic_or_organ_specific_conditions.condition_date_1",
    
    # infections severity
    "severity_field": "infections_initial_form.infection_severity",
    # condition severity
    #"severity_field_2": "patients_systemic_or_organ_specific_conditions.condition_severity",
    
    "modifier_field_1": "infections_initial_form.type_of_infection",
    "modifier_field_2": "infections_initial_form.infection_temp_pattern",
    "modifier_field_4": "infections_initial_form.causing_agent_viral",
    "modifier_field_5": "infections_initial_formcausing_agent_bacterial",
    "modifier_field_6": "infections_initial_form.causing_agent_mycotic",
    "modifier_field_7": "infections_initial_form.causing_organism_other",
    # condition modifiers
    # "modifier_field_8": "patients_systemic_or_organ_specific_conditions.type_of_condition",
    # "modifier_field_9": "patients_systemic_or_organ_specific_conditions.hp_0012539_modifier",
    # "modifier_field_10": "patients_systemic_or_organ_specific_conditions.hp_0012189_modifier",
    # "modifier_field_11": "patients_systemic_or_organ_specific_conditions.hp_0005523_modifier",
    # "modifier_field_12": "patients_systemic_or_organ_specific_conditions. condition_temp_patter",
    # "evidence_field": "patients_systemic_or_organ_specific_conditions.mondo_0005265_evidence",
    "multi_onset": True
}

        # "phenotypicFeatures": {
        #     # "instrument_configs": {
        #     #     "infections_initial_form": INFECTIONS_FEATURES_BLOCK,
        #     #     #"patients_systemic_or_organ_specific_conditions": CONDITIONS_FEATURES_BLOCK
        #     # },
        #     "instrument_name": "infections_initial_form",
        #     "label_dicts": {
        #         "TemporalPattern": label_dicts.get("TemporalPattern", {}),
        #         "PhenotypeSeverity": label_dicts.get("PhenotypeSeverity", {})
        #     },
        #     "mapping_block": PHENOTYPIC_FEATURES_BLOCK,
        #     "mapping_dicts": {
        #         "phenotypic_feature_status": mapping_dict_lookup.get("phenotypic_feature_status", {})
        #     },
        #     "enum_classes": {
        #         # Infections
        #         "type_of_infection": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.InfectionTypeEnum",
        #         "snomedct_61274003": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.OpportunisticInfectionEnum",
        #         "snomedct_21483005": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.CNSInfectionEnum",
        #         "snomedct_81745001": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.EyeInfectionEnum",
        #         "snomedct_385383008": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.ENTInfectionEnum",
        #         "snomedct_127856007": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.SkinInfectionEnum",
        #         "snomedct_110522009": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.BoneJointInfectionEnum",
        #         "snomedct_20139000": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.RespiratoryInfectionEnum",
        #         "snomedct_303699009": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.GIInfectionEnum",
        #         "snomedct_21514008": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.GUInfectionEnum",
        #         "snomedct_31099001": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.SystemicInfectionEnum",
        #         "infection_severity": "cieinr.v1_0_0.python_schemas.form_3_infections_initial.InfectionSeverityEnum",
        #         # Conditions
        #         # "type_of_condition": "cieinr.v1_0_0.python_schemas.form_4_conditions.ConditionTypeEnum",
        #         # "snomedct_95320005": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_118938008": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_50043002": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_49601007": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "mondo_0005570": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_928000": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_119292006": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "mondo_0005265_evidence": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_362969004": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_42030000": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_55342001": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_85828009": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "hp_0025142": "cieinr.v1_0_0.python_schemas.form_4_conditions.",
        #         # "snomedct_5294002": "cieinr.v1_0_0.python_schemas.form_4_conditions."
        #     }