PHENOTYPIC_FEATURES_BLOCK = {
    "redcap_repeat_instrument": "infections_initial_form",
    "type_field": "snomedct_61274003",
    "type_field_2": "snomedct_21483005",
    "type_field_3": "snomedct_81745001",
    "type_field_4":" snomedct_385383008",
    "type_field_5": "snomedct_127856007",
    "type_field_6": "snomedct_110522009",
    "type_field_7": "snomedct_20139000",
    "type_field_8": "snomedct_303699009",
    "type_field_9": "snomedct_21514008",
    "type_field_10":"snomedct_31099001",
    "type_field_11": "other_infection_hpo",
    "type_field_12": "other_infection_mondo",
    "excluded_field": None,
    "onset_date_fields": ["infection_date", "infection_date_2", 
                          "infection_date_3", "infection_date_4", 
                          "infection_date_5", "infection_date_6", 
                          "infection_date_7", "infection_date_8", 
                          "infection_date_9", "infection_date_10"],
    "resolution_field": None,
    "severity_field": "infection_severity",
    "modifier_field_1": "type_of_infection",
    "modifier_field_2": "infection_temp_pattern",
    "modifier_field_4": "causing_agent_viral",
    "modifier_field_5": "causing_agent_bacterial",
    "modifier_field_6": "causing_agent_mycotic",
    "modifier_field_7": "causing_organism_other",
    "evidence_field": None,
    "multi_onset": True  
}