name: CLI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write # Ensures GitHub Actions can commit to the repository

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true   # Ensures submodules are checked out

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --editable .[test,docs]
          python -m pip install --editable ./submodules/phenopacket_mapper  # Install the submodule package

      # Step 4: Run CLI tests and generate badge
      - name: Run CLI Tests and Generate Badge
        run: |
          mkdir -p rarelink/tests/cli/  # Ensure the directory exists
          if pytest tests/cli/; then
            echo '{"schemaVersion": 1, "label": "RareLink CLI", "message": "running", "color": "blue"}' > rarelink/tests/cli/status.json
          else
            echo '{"schemaVersion": 1, "label": "RareLink CLI", "message": "offline", "color": "orange"}' > rarelink/tests/cli/status.json
          fi


      # Step 5: Commit and push the badge status
      - name: Push Badge Status
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Update badge status"
          add: rarelink/tests/cli/status.json
