name: RareLink CLI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --editable .[test]

      # Step 4: Run pytest for CLI tests
      - name: Run CLI Tests
        run: |
          mkdir -p rarelink/tests/cli  # Ensure the directory exists
          if pytest rarelink/tests/cli; then
            echo '{"schemaVersion": 1, "label": "RareLink CLI", "message": "passing", "color": "blue"}' > rarelink/tests/cli/status.json
          else
            echo '{"schemaVersion": 1, "label": "RareLink CLI", "message": "failing", "color": "red"}' > rarelink/tests/cli/status.json
          fi

      # Step 5: Upload status.json as an artifact (optional for debugging)
      - name: Upload status.json
        uses: actions/upload-artifact@v3
        with:
          name: cli-status
          path: rarelink/tests/cli/status.json
