name: 🐍 Publish package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write    # required for OIDC

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build distributions
        run: |
          python -m pip install build
          python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
