name: Python CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true   # This ensures submodules are checked out      - name: Checkout code
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --editable .[test,docs]
          python3 -m pip install --editable ./submodules/phenopacket_mapper  # Install the submodule package
          
      - name: Run tests with pytest
        run: |
          pytest
